class Skill < ApplicationRecord
  has_many :project_skills
  has_many :projects, through: :project_skills
  SKILLS = [
  "Ruby",
  "JavaScript",
  "HTML",
  "CSS",
  "SQL",
  "Ruby on Rails",
  "Hotwire",
  "Turbo",
  "Stimulus",
  "PostgreSQL",
  "MySQL",
  "SQLite",
  "RSpec",
  "Capybara",
  "Selenium",
  "Git",
  "Docker",
  "Webpack",
  "Heroku",
  "RESTful APIs",
  "GraphQL",
  "Enseñanza",
  "Presentaciones",
  "Trabajo en equipo",
  "Mentoría",
  "Metodologías Ágiles",
  "Trello",
  "Jira",
  "Seguridad (OWASP)",
  "Autenticación",
  "Autorización",
  "Pundit",
  "Optimización y Rendimiento",
  "Caching",
  "Optimización de consultas",
  "Diseño Responsivo",
  "Experiencia del Usuario",
  "Background Jobs",
  "Sidekiq",
  "Websockets",
  "Action Cable",
  "Search",
  "jQuery",
  "Templating",
  "AJAX",
  "Bootstrap",
  "Parsing",
  "Scraping",
  "Active Record"
]

end
